"""empty message

Revision ID: 0d0a59fd9c36
Revises: d753e024a326
Create Date: 2019-12-09 16:43:34.732826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0a59fd9c36'
down_revision = 'd753e024a326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['lastname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###
