"""empty message

Revision ID: 369f5269aabe
Revises: 5b021f14f91f
Create Date: 2019-12-12 10:36:37.161452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369f5269aabe'
down_revision = '5b021f14f91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
