"""empty message

Revision ID: 45684c00fec7
Revises: 270a07b0a9b0
Create Date: 2019-12-10 08:55:03.979736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45684c00fec7'
down_revision = '270a07b0a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
