"""empty message

Revision ID: 5b021f14f91f
Revises: 45684c00fec7
Create Date: 2019-12-11 14:03:31.516069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b021f14f91f'
down_revision = '45684c00fec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_index('lastname', table_name='users')
    op.drop_index('name', table_name='users')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_index('lastname', 'users', ['lastname'], unique=True)
    op.add_column('tasks', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
