"""empty message

Revision ID: 930357e7ee2f
Revises: 369f5269aabe
Create Date: 2019-12-12 10:48:49.448685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '930357e7ee2f'
down_revision = '369f5269aabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.String(length=50), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
