"""empty message

Revision ID: c71097c70311
Revises: 930357e7ee2f
Create Date: 2019-12-12 10:50:42.639988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c71097c70311'
down_revision = '930357e7ee2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
